### ISSUE TITLE
Names in RarFile.names contain carriage return on Windows

### ISSUE THREAD

**Issue by nounuikg** [sandy98/node-rarfile#2]
When interpreting the output from unrar, you split the list of names on '\n' and return the resulting array.

On Windows, newlines are '\r\n', not just '\n', so the '\r' character is still present in each string that gets returned.

As a result, if you pass, say, RarFile.names[0] to RarFile.readFile, unrar doesn't find the requested file, and doesn't return anything.

You should remove the carriage return before returning the list of names.

**Comment by sandy98** [comment]
I think it's corrected now. 
I'd appreciate if you can check it in Windows and let me know.
Thanks
